# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    permissions:
      packages: write
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: NuGet create package
      run: dotnet pack 
      working-directory: PowerCollections
      
    - name: NuGet publish package
      run: dotnet nuget push "\PowerCollections\bin\Debug\*.nupkg" --api-key  ${{ secrets.GITHUB_TOKEN }}  --source https://nuget.pkg.github.com/Lokeryt/index.json --skip-duplicate
      working-directory: PowerCollections
      
    - name: get xml
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'PowerCollections\PowerCollections\PowerCollections.csproj'
        xpath: '//Version'

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\Lokeryt.PowerCollections.${{ steps.getxml.outputs.info }}.nupkg'
        tag: 'v${{ steps.getxml.outputs.info }}'
        token:  ${{ secrets.GITHUB_TOKEN }} 
